server.port=${PORT:8080}
spring.application.name=text-to-sql
spring.datasource.url=jdbc:sqlite:db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.initialization-mode=always
# Keep Hibernate off; using JdbcTemplate
